version: '3'
services:

  vpu111.nginx.router:
    image: nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - vpu111.front.admin
      - vpu111.front.public
      - vpu111.api.laravel
      - vpu111.api.node
      - vpu111.api.node.jonny
      - vpu111.api.node.sunny
      - vpu111.storage
    networks:
      - vpu111

  vpu111.api.laravel:
    build: ./back/laravel
    ports:
      - '8000:8000'
    volumes:
      - './back/laravel/src:/app'
    networks:
      - vpu111

  vpu111.api.node:
    build: ./back/node
    working_dir: /app
    command: sh -c "npm install && npm run start"
    environment:
      - SERVER_NAME=api.node
      - SERVER_PORT=3003
    ports:
      - '3003:3003'
    volumes:
      - './back/node/src:/app'
    networks:
      - vpu111

  vpu111.api.node.sunny:
    build: ./back/node
    working_dir: /app
    command: sh -c "npm install && npm run start"
    environment:
      - SERVER_NAME=api.node.sunny
      - SERVER_PORT=3005
    ports:
      - '3005:3005'
    volumes:
      - './back/node/src:/app'
    networks:
      - vpu111

  vpu111.api.node.jonny:
    build: ./back/node
    working_dir: /app
    command: sh -c "npm install && npm run start"
    environment:
      - SERVER_NAME=api.node.jonny
      - SERVER_PORT=3006
    ports:
      - '3006:3006'
    volumes:
      - './back/node/src:/app'
    networks:
      - vpu111


  vpu111.front.admin:
    build: ./front/admin
    ports:
      - '5173:5173'
    volumes:
      - './front/admin/src:/app'
    networks:
      - vpu111

  vpu111.front.public:
    build: ./front/public
    ports:
      - '3000:3000'
    volumes:
      - './front/public/src:/app'
    networks:
      - vpu111

  vpu111.db.mysql.main:
    container_name: vpu111.db.mysql.main
    image: mysql
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - vpu111

  vpu111.storage:
    container_name: vpu111.storage
    image: minio/minio:latest
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    networks:
      - vpu111

networks:
  vpu111:
    driver: bridge