version: '3'
services:

  api.laravel:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile_developer
    networks:
      - vpu111_net

  api.spring:
    build: ./backend/spring/api/
    networks:
      - vpu111_net

  vpu111.mysql.db:
    # Образ будет браться сразу с репозитория
    # Указывание версии сервера положительно отразиться на коде
    # Тут создается только сервер баз данных
    # image: mysql:8.3

    # Промежуточный докер файл позвоит выполнять операции
    # До сборки контейнера
    build:
      dockerfile: ./services/mysql/Dockerfile
      context: .
    # https://hub.docker.com/_/mysql Environment Variables
    # Оптимальным является вынос настроек в отдельный файл конфигурации
    # Или под каждый сервис - или 1 для всех
    env_file:
      - db.env
    # Не обязательный параметр - который покажет сеть (окружение докера)
    # внутри которой будет база доступна
    networks:
      - vpu111_net
    # Не обязательный параметр - фиксирующий имя контейнера
    container_name: vpu111.mysql.db
    # Что бы не плодить диски - лучше указать - где именно будет
    # располагаться файлы базы
    # Это не обязательный параметр
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3310:3306"

  vpu111.phpmyadmin:
    image: phpmyadmin
    ports:
      - "8088:80"
    env_file:
      - db.env
    networks:
      - vpu111_net

networks:
  vpu111_net:
    driver: bridge